# 配置文件

# 请求相关配置
REQUEST_TIMEOUT = 30  # 请求超时时间，单位：秒

# 其他可能需要的配置项
HEADLESS = False
CDP_HEADLESS = True
ENABLE_IP_PROXY = False
IP_PROXY_POOL_COUNT = 5
ENABLE_CDP_MODE = False
SAVE_LOGIN_STATE = False
CUSTOM_BROWSER_PATH = None
CDP_DEBUG_PORT = 9222
BROWSER_LAUNCH_TIMEOUT = 60